name: pangeo
channels:
  - conda-forge
dependencies:
  - python=3.7*
  - pangeo-notebook=2020.06.19
  - pip=20
  - bokeh>=2.1.1
  - cartopy
  - ciso
  - cmocean
  - dask-ml
  - datashader
  - descartes
  - fastparquet
  - fsspec
  - gcsfs
  - geopandas
  - geoviews-core
  - h5netcdf
  - h5py
  - holoviews
  - hvplot
  - intake
  - intake-esm
  - intake-geopandas
  - intake-stac
  - intake-xarray
  - ipyleaflet
  - ipywidgets
  - jupyter-panel-proxy
  - lz4
  - matplotlib-base
  - metpy
  - nc-time-axis
  - netcdf4
  - nomkl
  - numba==0.49.0
  - numcodecs
  - numpy
  - pandas
  - panel
  - prefect
  - pyarrow
  - pydap
  - pynio
  - python-blosc
  - pykdtree==1.3.1
  - pyresample==1.10.2
  - rasterio
  - rio-cogeo
  - s3fs
  - sat-search
  - sat-stac
  - satpy
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - sparse
  - tiledb-py
  - xarray
  - xcape
  - xesmf
  - xgcm
  - xhistogram
  - xlayers
  - xmitgcm
  - xpublish
  - xrft
  - zarr
  - pip:
      - ccmet
      - "prefect[viz]"
      - rechunker
