#!/bin/bash
jupyter labextension install --clean --minimize=False \
                             @jupyter-widgets/jupyterlab-manager \
                             @pyviz/jupyterlab_pyviz \
                             dask-labextension \
                             jupyter-leaflet \
                             @jupyterlab/toc 
#EOF
