#!/bin/bash

jupyter labextension install --clean \
                            @jupyter-widgets/jupyterlab-manager \
                            @pyviz/jupyterlab_pyviz \
                            jupyter-leaflet \
                            dask-labextension 

#EOF
